### PR TITLE
CGAL Plugin; 

### PR DESCRIPTION
**Pull request by Samarean**
several fixes (double vertices;bad loading, etc.)
new meshes; still debugging testcase cube

### CODE REVIEW

**Comment by Samarean** [comment]
Reconstruction from point sets also disables the tdr plugin

**Comment by Samarean** [comment]
hey florian,

falls du morgen da bist, werde ich so kurz vorbeikommen, um die letzten
dinge zu besprechen.

LG Peter

2015-09-03 16:15 GMT+02:00 FlorianRudolf <notifications@github.com>:

**Comment by karlrupp** [comment]
Sorry, Florian is not around tomorrow. Please stick to English here :-)

**Comment by Samarean** [comment]
sorry, i used the wrong mail to reply
Am 03.09.2015 21:22 schrieb "Karl Rupp" <notifications@github.com>:

**Pull request merged**
